name: Build Samsung G611F Kernel

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/aum47/android_kernel_samsung_g611f
          kernel-branch: main
          config: on7xreflte_01_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r383902
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          extra-cmd: "KCFLAGS='-Wno-error -Wno-zero-length-bounds -Wno-stringop-truncation -Wno-switch-unreachable'"
