name: Build Kernel (mrproper + noninteractive + system-dtc)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      android_major:
        description: "Android major version (p=Android 9, r=Android 11)"
        required: false
        default: "p"
      defconfig:
        description: "Kernel defconfig under arch/arm64/configs"
        required: false
        default: "on7xreflte_01_defconfig"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    # Provide safe defaults even on 'push' (where workflow_dispatch defaults don't apply)
    env:
      DEFCONFIG: ${{ github.event.inputs.defconfig || 'on7xreflte_01_defconfig' }}
      ANDROID_MAJOR: ${{ github.event.inputs.android_major || 'p' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev \
            libncurses5-dev libncursesw5-dev dwarves git \
            device-tree-compiler \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
        # GNU make needs valid file/target arguments; empty values can cause "empty string invalid as file name" errors, so we ensure defaults above. [web:333][web:331]

      - name: Kernel mrproper (source root)
        run: |
          make mrproper
        # mrproper fully cleans generated files before an out-of-tree build per Kbuild expectations. [web:203][web:195]

      - name: Configure (ARM64, non-interactive)
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION="${ANDROID_MAJOR}"
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          make O=out "${DEFCONFIG}"
          make O=out olddefconfig
        # olddefconfig finalizes any new symbols without prompts, keeping CI non-interactive. [web:285][web:321]

      - name: Build (use system dtc + -fcommon for host tools)
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION="${ANDROID_MAJOR}"
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          make O=out DTC=dtc HOSTCFLAGS="-fcommon" -j"$(nproc)"
          ls -al out/arch/arm64/boot || true
        # For older in-tree dtc, -fcommon avoids the yylloc duplicate symbol with modern toolchains; using DTC=dtc selects the system device-tree-compiler. [web:314][web:315][web:222]

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ github.run_number }}
          if-no-files-found: warn
          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/dts/**/*.dtb
            out/drivers/**/*.ko
