name: Kernel Build (G611F)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex git gcc clang \
          libncurses5-dev libssl-dev lld llvm make python3 unzip zip wget ccache

    - name: Download Toolchain
      run: |
        mkdir -p ~/toolchains
        cd ~/toolchains
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=~/toolchains/clang/bin/aarch64-linux-gnu-
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export PATH=~/toolchains/clang/bin:$PATH
        export ANDROID_MAJOR_VERSION=r
        
        mkdir -p out
        make O=out on7xreflte_01_defconfig
        make -j$(nproc) O=out Image.gz-dtb

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: G611F-Kernel
        path: out/arch/arm64/boot/Image.gz-dtb
