name: Build Kernel (Android 9)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev \
            libncurses5-dev libncursesw5-dev dwarves git

      - name: Fetch Android GCC 4.9 toolchains (arm64 + arm32)
        run: |
          set -e
          mkdir -p toolchains
          # ARM64 (Android Pie-era prebuilts)
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 toolchains/aarch64-4.9
          cd toolchains/aarch64-4.9
          # Use a known ref containing binaries; Android 9 tags exist in this repo
          git checkout android-9.0.0_r61 || git rev-parse HEAD
          cd ../../
          # ARM32 companion (often required by arm64 kernels)
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 toolchains/arm32-4.9
          cd toolchains/arm32-4.9
          git checkout android-9.0.0_r61 || git rev-parse HEAD
          cd ../../
          echo "$GITHUB_WORKSPACE/toolchains/aarch64-4.9/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/toolchains/arm32-4.9/bin"   >> $GITHUB_PATH

      - name: Print compiler versions
        run: |
          aarch64-linux-android-gcc --version || true
          arm-linux-androideabi-gcc --version || true

      - name: Configure (ARM64, Pie)
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION=p
          export CROSS_COMPILE="$GITHUB_WORKSPACE/toolchains/aarch64-4.9/bin/aarch64-linux-android-"
          export CROSS_COMPILE_ARM32="$GITHUB_WORKSPACE/toolchains/arm32-4.9/bin/arm-linux-androideabi-"
          make O=out on7xreflte_01_defconfig

      - name: Build
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION=p
          export CROSS_COMPILE="$GITHUB_WORKSPACE/toolchains/aarch64-4.9/bin/aarch64-linux-android-"
          export CROSS_COMPILE_ARM32="$GITHUB_WORKSPACE/toolchains/arm32-4.9/bin/arm-linux-androideabi-"
          make O=out -j"$(nproc)"
          ls -al out/arch/arm64/boot || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ github.run_number }}
          if-no-files-found: warn
          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/dts/**/*.dtb
            out/drivers/**/*.ko
