name: Build Kernel (fix mrproper + dtc)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Prevent earlier runs from being auto-canceled when new pushes happen
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev \
            libncurses5-dev libncursesw5-dev dwarves \
            device-tree-compiler gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Kernel mrproper (source root)
        run: |
          make mrproper
        # Clean tree so headers/symlinks regenerate correctly for O=out builds
        # per Kbuild rules.
        # (No O= here; run at repo root.)
        # 
        # References: make help / Kbuild docs.

      - name: Configure (ARM64)
        timeout-minutes: 30
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          # Set this to 'p' for Android 9 or 'r' for Android 11 as needed:
          export ANDROID_MAJOR_VERSION=p
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          make O=out on7xreflte_01_defconfig
          # Resolve any new symbols non-interactively:
          make O=out olddefconfig

      - name: Build
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION=p
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          # Use system dtc to avoid yylloc conflicts with in-tree dtc:
          make O=out DTC=dtc -j"$(nproc)"
          ls -al out/arch/arm64/boot || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ github.run_number }}
          if-no-files-found: warn
          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/dts/**/*.dtb
            out/drivers/**/*.ko
